name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set Terraform Variables
        run: |
          echo 'subscription_id="${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}"' >> terraform.auto.tfvars
          echo 'tenant_id="${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"' >> terraform.auto.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
